export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'
export const GET_USER_AND_REPOS = 'GET_USER_AND_REPOS'
export const SET_LOADING = 'SET_LOADING'
export const CLEAR_USERS = 'CLEAR_USERS'